#!/bin/bash

# This calls our custom branding script
jamf policy -event custombrand

# This writes our configs for NoMAD Login and NoMAD
jamf policy -event nomadconfig

# This installs Nomad
jamf policy -event nomad

killall -HUP loginwindow


# Wait for user to be logged in

dockStatus=$(pgrep -x Dock)
log "Waiting for Desktop"
while [ "$dockStatus" == "" ]; do
  log "Desktop is not loaded. Waiting."
  sleep 2
  dockStatus=$(pgrep -x Dock)
done

# more installs below
jamf policy -event filluser
jamf policy -event cvhelp
jamf policy -event dockfix

# set computer name
# jamf policy -event setname
